In [2]:
import numpy as np 

**Question No 1**:
Write a NumPy program to create an array of all even integers from 30 to 70.

In [4]:
# Making array of even numbers from 30 to 70
even_array = np.arange(30, 71, 2)

print("Array: ", even_array)

Array:  [30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]


**Question no 2**:
Write a NumPy program to generate an array of 15 random numbers from a standard normal
distribution.

In [5]:
# Generating array of 15 random numbers from a standard normal distribution
rand_array = np.random.randn(15)

print("Array:", rand_array)

Array: [ 1.14755876 -0.26946403  0.93858462  1.11035514 -0.14288418  1.07576284
 -0.43843071  2.31879371  0.51410123  0.26928817 -1.39784655  1.18468941
 -0.1244735  -0.27437115 -0.59540891]


**Question no 3**:
How to compute the cross-product of two matrices in NumPy?

In [8]:
m1 = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])

m2 = np.array([[9, 8, 7],
                    [6, 5, 4],
                    [3, 2, 1]])

# cross-product of the two matrices
cross_product = np.cross(m1, m2)

print("Cross-product:")
print(cross_product)

Cross-product:
[[-10  20 -10]
 [-10  20 -10]
 [-10  20 -10]]


**Question no 4**:
How to compute the determinant of an array using NumPy?

In [9]:
matrix = np.array([[4, 7],
                   [2, 6]])

# Computing determinant
value = np.linalg.det(matrix)

print("Determinant:")
print(value)

Determinant:
10.000000000000002


**Question no 5**:
How to create a 3x3x3 array with random values using NumPy?

In [3]:
# Creating 3x3x3 array
random_array = np.random.rand(3, 3, 3)

print("Array:")
print(random_array)

Array:
[[[0.97387842 0.84764848 0.16456777]
  [0.05165983 0.67105339 0.29349973]
  [0.60606283 0.91710359 0.83672196]]

 [[0.36277173 0.84127889 0.65021227]
  [0.19868695 0.86791794 0.84962239]
  [0.65319343 0.47082129 0.11928278]]

 [[0.48589758 0.03471758 0.05375667]
  [0.75866024 0.86081838 0.72072378]
  [0.85858896 0.91083811 0.23091408]]]


**Question no 6**:
How to create a 5x5 array with random values and find the minimum and maximum values using
NumPy?

In [11]:
#array with random values
random_array = np.random.rand(5, 5)

print("Array:")
print(random_array)

# Find the minimum and maximum values
min_value = np.min(random_array)
max_value = np.max(random_array)

print("\nMinimum value:", min_value)
print("Maximum value:", max_value)

Array:
[[0.486482   0.02359723 0.54746936 0.13517853 0.10795646]
 [0.90600445 0.96441383 0.64129036 0.7564463  0.56626065]
 [0.11183928 0.6093426  0.93336371 0.89931969 0.44324311]
 [0.02850598 0.32300096 0.2242151  0.45986438 0.67357317]
 [0.64341498 0.46139754 0.1051794  0.38411565 0.28838338]]

Minimum value: 0.023597228394296343
Maximum value: 0.9644138276444056


**Question no 7**:

How to compute the mean, standard deviation, and variance of a given array along the second axis in
NumPy?

In [15]:
array = np.array([[6, 2, 8],
                  [4, 9, 6],
                  [7, 8, 5]])

# Computing mean
mean = np.mean(array, axis=1)

# Computing the standard deviation
std_dev = np.std(array, axis=1)

# Computing the variance
variance = np.var(array, axis=1)

print("Mean along the second axis: ", mean)
print("\nStandard deviation along the second axis:")
print(std_dev)
print("\nVariance along the second axis:")
print(variance)

Mean along the second axis:  [5.33333333 6.33333333 6.66666667]

Standard deviation along the second axis:
[2.49443826 2.05480467 1.24721913]

Variance along the second axis:
[6.22222222 4.22222222 1.55555556]
